---
- name: Ensure maven directory
  file:
    path: "/home/deploy/.m2"
    state: directory
    owner: deploy
    group: deploy

- name: Copy maven settings for dev-local
  template:
    src: templates/settings.xml.j2
    dest: /home/deploy/.m2/settings.xml
