(ns kefirnadar.application.regions)

(def regions [:Ada
              :Aleksandrovac
              :Aleksinac
              :Alibunar
              :Apatin
              :Aranđelovac
              :Arilje
              :Babušnica
              :Bajina-Bašta
              :Batočina
              :Bač
              :Bačka-Palanka
              :Bačka-Topola
              :Bački-Petrovac
              :Beograd
              :Bela-Palanka
              :Bela-Crkva
              :Beočin
              :Bečej
              :Blace
              :Bogatić
              :Bor
              :Bojnik
              :Boljevac
              :Bosilegrad
              :Brus
              :Bujanovac
              :Varvarin
              :Valjevo
              :Vranje
              :Vršac
              :Velika-Plana
              :Veliko-Gradište
              :Vitina
              :Vladimirci
              :Vladičin-Han
              :Vlasotince
              :Vrbas
              :Vrnjačka-Banja
              :Vučitrn
              :Gadžin-Han
              :Glogovac
              :Gnjilane
              :Golubac
              :Gora
              :Gornji-Milanovac
              :Despotovac
              :Dečani
              :Dimitrovgrad
              :Doljevac
              :Đakovica
              :Žabalj
              :Žabari
              :Žagubica
              :Žitište
              :Žitorađa
              :Zvečan
              :Zaječar
              :Zrenjanin
              :Zubin-Potok
              :Ivanjica
              :Inđija
              :Irig
              :Istok
              :Jagodina
              :Kikinda
              :Kragujevac
              :Kraljevo
              :Kruševac
              :Kanjiža
              :Kačanik
              :Kladovo
              :Klina
              :Knić
              :Knjaževac
              :Kovačica
              :Kovin
              :Kosjerić
              :Kosovo-Polje
              :Kosovska-Kamenica
              :Kosovska-Mitrovica
              :Koceljeva
              :Krupanj
              :Kula
              :Kuršumlija
              :Kučevo
              :Leskovac
              :Loznica
              :Lajkovac
              :Lapovo
              :Lebane
              :Leposavić
              :Lipljan
              :Lučani
              :Ljig
              :Ljubovija
              :Majdanpek
              :Mali-Zvornik
              :Mali-Iđoš
              :Malo-Crniće
              :Medveđa
              :Merošina
              :Mionica
              :Negotin
              :Niš
              :Novi-Pazar
              :Novi-Sad
              :Nova-Varoš
              :Nova-Crnja
              :Novi-Bečej
              :Novi-Kneževac
              :Novo-Brdo
              :Obilić
              :Opovo
              :Orahovac
              :Osečina
              :Odžaci
              :Paraćin
              :Pančevo
              :Pirot
              :Požarevac
              :Priština
              :Petrovac-na-Mlavi
              :Peć
              :Pećinci
              :Plandište
              :Podujevo
              :Prokuplje
              :Požega
              :Preševo
              :Priboj
              :Prizren
              :Prijepolje
              :Ražanj
              :Rača
              :Raška
              :Rekovac
              :Ruma
              :Svilajnac
              :Svrljig
              :Smederevo
              :Sombor
              :Senta
              :Sečanj
              :Sjenica
              :Smederevska-Palanka
              :Sokobanja
              :Srbica
              :Srbobran
              :Sremski-Karlovci
              :Sremska-Mitrovica
              :Stara-Pazova
              :Subotica
              :Suva-Reka
              :Surdulica
              :Temerin
              :Titel
              :Topola
              :Trgovište
              :Trstenik
              :Tutin
              :Ćićevac
              :Ćuprija
              :Ub
              :Užice
              :Uroševac
              :Crna-Trava
              :Čajetina
              :Čačak
              :Čoka
              :Šabac
              :Šid
              :Štimlje
              :Štrpce])
