---
- name: Ensure project directories
  file:
    path: "{{ item }}"
    state: directory
    owner: deploy
    group: deploy
  with_items:
    - "{{ project_dir }}"
    - "{{ project_dir }}/build/target/"
    - "{{ project_dir }}/public/js/"

- name: Copy kefirnadar jar, public assets and config
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: deploy
    group: deploy
  with_items:
    - { src: "../target/kefirnadar.jar", dest: "{{ project_dir }}/build/target/kefirnadar.jar" }
    - { src: "../resources/public/js/main.js", dest: "{{ project_dir }}/public/js/main.js" }
    - { src: "../resources/public/index.html", dest: "{{ project_dir }}/public/index.html" }
    - { src: "../resources/public/images", dest: "{{ project_dir }}/public" }

- name: Copy kefirnadar service definition
  template: 
    src: templates/kefirnadar.service.j2
    dest: /lib/systemd/system/kefirnadar.service

- name: Enable kefirnadar service
  command: systemctl enable /lib/systemd/system/kefirnadar.service
  notify: restart kefirnadar
